version: '3'
services:
  backend:
    image: krisenberg/backend:latest
    container_name: backend
    ports:
      - "8080:80"
    environment:
      - FRONTEND_IP=http://glowacz-ttt.us-east-1.elasticbeanstalk.com:3000
  frontend:
    image: krisenberg/frontend:cognito
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_IP=http://glowacz-ttt.us-east-1.elasticbeanstalk.com:8080
      - REACT_APP_COGNITO_REGION=${REACT_APP_COGNITO_REGION}
      - REACT_APP_COGNITO_USER_POOL_CLIENT_ID=${REACT_APP_COGNITO_USER_POOL_CLIENT_ID}
      - REACT_APP_COGNITO_USER_POOL_ID=${REACT_APP_COGNITO_USER_POOL_ID}